First iteration
Anatoly8853/42-docker-final-main pull request #1
Opened 2024-08-21 18:02 UTC by Anatoly8853

2024-08-21 20:21 UTC, dirtymew requested changes
Привет Анатолий

дал комментарии что поправить

2024-08-21 20:21 UTC, dirtymew commented on Dockerfile
>  FROM golang:1-alpine
лучше зафиксировать образ с нужной версией go  - golang:1.22-alpine

2024-08-21 20:21 UTC, dirtymew commented on Dockerfile
>  RUN apk add --no-cache && go mod tidy
apk add --no-cache ? зачем - лишнее мне кажется

2024-08-21 20:21 UTC, dirtymew commented on Dockerfile
>  RUN apk add --no-cache && go mod tidy
go mod tidy - лучше go mod download

2024-08-21 20:21 UTC, dirtymew commented on Dockerfile
>  RUN apk add --no-cache && go mod tidy
и нужно еще собрать приложение и запустить

2024-08-22 10:04 UTC, Anatoly8853 commented on Dockerfile
>  FROM golang:1-alpine
При такой сборки проект на почти 50 мег больше

2024-08-22 12:37 UTC, dirtymew requested changes
Анатолий

еще есть ошибки - нужно поправить

2024-08-22 12:37 UTC, dirtymew commented on Dockerfile
> +CMD ["./ProjectAvp"]
```
# Сборка исполняемого файла
RUN go build -o ./projectAvp

# Запуск исполняемого файла
CMD ["./projectAvp"]

```
- приложение сейчас не запускается в контейнере
- в linux как-то не принято приложения с большой буквы называть

2024-08-22 15:21 UTC, dirtymew approved these changes
Анатолий

все супер - зачет

2024-08-22 16:09 UTC, closed without merging